# Generated by Django 5.2.7 on 2025-10-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicinebot', '0002_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='original_query_text',
            new_name='search_query',
        ),
        migrations.RemoveField(
            model_name='history',
            name='medicine_name',
        ),
        migrations.AlterField(
            model_name='history',
            name='analysis_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
