"""
Django settings for medguard_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-cvq02y1lhxd2r3^t%#dd&%+i)axoh87)v4q#8%+mxc!hv7wx*m") # Default for safety

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True" # Default to True for dev

ALLOWED_HOSTS = ['*'] # Be more specific in production


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "medicinebot", # Your app
    # You might not need corsheaders if running locally, keep if deploying
    # "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # "corsheaders.middleware.CorsMiddleware", # Only if needed
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# If using corsheaders:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:8001",
#     "http://127.0.0.1:8001",
# ]
# CORS_ALLOW_ALL_ORIGINS = False # Or True if needed for development

ROOT_URLCONF = "medguard_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'], # Optional: Project-level templates
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "medguard_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i1n/

LANGUAGE_CODE = "en-us"

# --- TIME ZONE FIX ---
TIME_ZONE = "Asia/Kolkata" # Set your local time zone

USE_I18N = True

# --- TIME ZONE FIX ---
USE_TZ = True # Keep this True to store UTC in DB


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
# Optional: Define STATICFILES_DIRS if you have project-level static files
# STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- Login/Logout Redirects ---
LOGIN_REDIRECT_URL = 'home' # Where to go after successful login
LOGOUT_REDIRECT_URL = 'login' # Where to go after logout
LOGIN_URL = 'login' # The name of your login URL pattern

# --- Custom Paths ---
# Correct path assuming MajorProjectDataset.csv is OUTSIDE medguard_project folder
MEDICINE_DATA_PATH = BASE_DIR.parent / "MajorProjectDataset.csv"
# Define where the search index will be stored inside the project folder
INDEX_STORAGE_PATH = BASE_DIR / "storage"

# Ensure the storage directory exists
os.makedirs(INDEX_STORAGE_PATH, exist_ok=True)

